env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - unused-imports
  - vue
rules:
  no-unused-vars: 'off'
