name: 非预期行为和漏洞
description: 提交一个非预期行为和漏洞报告。
#title:
labels:
  - bug
  - question
assignees:
  - Arondight
body:
  - type: markdown
    attributes:
      value: |
        感谢您的提交，至少填写下方带红色星花标记的部分。
  - type: textarea
    id: question
    attributes:
      label: 问题描述
      description: 在此详细描述你遇到的非预期行为或漏洞。
      placeholder: 在此输入 Markdown 文本。
      #value:
    validations:
      required: true
  - type: textarea
    id: operation
    attributes:
      label: 复现流程
      description: 告诉我们如何操作才有可能重现你的问题，以便我们定位和解决。
      placeholder: 在此输入 Markdown 文本。
      #value:
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: 后台日志
      description: 运行命令 `npm run log` ，并将出现问题时后台输出的日志粘贴在此处。
      render: Text
      placeholder: 在粘贴日志文本，将被转化为代码块。
      #value:
    validations:
      required: false
  - type: textarea
    id: status
    attributes:
      label: 运行环境
      description: 将命令 `npm run tool-status` 输出粘贴在此处。
      render: Text
      placeholder: 在粘贴命令输出，将被转化为代码块。
      #value:
    validations:
      required: true
  - type: textarea
    id: git-log
    attributes:
      label: 当前提交
      description: 将命令 `git log -1` 输出粘贴在此处。
      render: Text
      placeholder: 在粘贴命令输出，将被转化为代码块。
      #value:
    validations:
      required: true
  - type: textarea
    id: git-status
    attributes:
      label: 代码状态
      description: 将命令 `git status` 输出粘贴在此处。
      render: Text
      placeholder: 在粘贴命令输出，将被转化为代码块。
      #value:
    validations:
      required: true
